package com.marakana.contacts.repositories;

import com.marakana.contacts.entities.Contact;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/**
 * Created by SERGE on 31.08.2014.
 */
public class ContactRepository {

    private final DataSource dataSource;

    public ContactRepository() {
        try {
            Context context = new InitialContext();
            try {
                dataSource = (DataSource) context.lookup("java:comp/env/jdbc/trainingdb");
            } finally {
                context.close();
            }

        } catch (NamingException e) {
            throw new RuntimeException(e);
        }

    }

    public void init() throws SQLException {
        Connection connection = dataSource.getConnection();
        try {
            Statement statement = connection.createStatement();
            try {
                statement.execute("create table contact (id integer generated by default as identity primary key, name varchar(255), address_id integer, foreign key(address_id) constraint address)");
            } finally {
                statement.close();
            }
        } finally {
            connection.close();
        }
    }

    public List<Contact> findAll() throws SQLException{
        return null; //TODO
    }

    public Contact find(long id) throws SQLException {
        Connection connection = dataSource.getConnection();
        try {
            Statement statement = connection.createStatement();
            try {
                ResultSet result = statement.executeQuery("select * from contact where id = " + id);
                try {
                    if (!result.next()) {
                        return null;
                    } else {
                        return unmarshal(result);
                    }
                } finally {
                    result.close();
                }

            } finally {
                statement.close();
            }
        } finally {
            connection.close();
        }

    }

    public void create(Contact contact) throws SQLException {
        Connection connection = dataSource.getConnection();
        try {
            Statement statement = connection.createStatement();
            try {
                statement.executeUpdate("insert into contact (name, address_id) values ('"
                                + contact.getName() + "', '" + contact.getAddressId() + "')",
                        Statement.RETURN_GENERATED_KEYS);

                ResultSet resultSet = statement.getGeneratedKeys();
                try {
                    if (resultSet.next())
                        contact.setId(resultSet.getLong("id"));
                } finally {
                    resultSet.close();
                }

            } finally {
                statement.close();
            }
        } finally {
            connection.close();
        }
    }

    public void update(Contact contact) throws SQLException {
        Connection connection = dataSource.getConnection();
        try {
            Statement statement = connection.createStatement();
            try {
                statement.executeUpdate("update contact set name = '"
                        + contact.getName() + "', address_id = '"
                        + contact.getAddressId() + "') where id = "
                        + contact.getId());
            } finally {
                statement.close();
            }
        } finally {
            connection.close();
        }
    }

    public void delete(Contact contact) throws SQLException {
        Connection connection = dataSource.getConnection();
        try {
            Statement statement = connection.createStatement();
            try {
                statement.executeUpdate("delete from contact where id = " + contact.getId());
            } finally {
                statement.close();
            }
        } finally {
            connection.close();
        }
    }

    private static Contact unmarshal(ResultSet results) throws SQLException {
        Contact contact = new Contact();
        contact.setId(results.getLong("id"));
        contact.setName(results.getString("name"));
        contact.setAddressId(results.getLong("address_id"));

        return contact;
    }


}
